### ISSUE TITLE
 Fatal error: Class 'PHPUnit_TextUI_Command' not found

### ISSUE THREAD

**Issue by willdurand** [padraic/humbug#17]
Hi!

Wanted to give humbug a try, got the following error:

```
<warning>Stdout: \n    >
    > Fatal error: Class 'PHPUnit_TextUI_Command' not found in /path/to/geocoder-php/Geocoder/vendor/humbug/humbug/src/Humbug/Adapter/Phpunit.php on line 157
    >
    > Call Stack:
    >     0.0003     219672   1. {main}() -:0
    >     0.0060     413624   2. Humbug\Adapter\Phpunit::main() -:8
    >
    > \n</warning>
```

Requiring `composer require phpunit/phpunit` solved the issue, so I think a dependency is missing in humbug, but maybe requiring `phpunit/phpunit` is too much.

Cheers,
William

**Comment by padraic** [comment]
Move this to require vs require-dev. Humbug uses it's own copy of PHPUnit for several things rather than hunting down others. One reason is that a number of packages out there are hard linked to old minor versions, e.g. monolog requires PHPUnit 3.7.* which has problems generating code coverage. Might up the ante on installing, but it means fewer oddball bugs being inherited.
