### ISSUE TITLE
Sneeky Mutants escaping when they shouldn't

### ISSUE THREAD

**Issue by carnage** [padraic/humbug#49]
I ran humbug over a (private) code base and the results were "disastrous" barely 10% of mutants were caught by my test suite. Looking at the log file, I went and added some of the mutations to the files manually in order to help improve coverage, however the tests now failed. 

The tests in question use a PHPunit data provider to provide different cases to test, I'm wondering if humbug's handling of data providers might be a bit wonky?

**Comment by padraic** [comment]
Any chance of a reproducible example?

I'd need to look into it, and I can't think of a reason why Humbug would be interfering, but that doesn't mean something is going on. The only items Humbug should be manipulating are the source code (never the test code), and it does use an edited copy of your phpunit.xml to run test classes in a fastest-first order.

Could you try running tests using the --tap option using phpunit - just to make sure it still reports those failures (by implanting the mutations) correctly? The TAP does need testing for more scenarios so it's one possible cause.

**Comment by carnage** [comment]
The --tap option shows failures properly, I'll try and construct a test case at the weekend.

**Comment by padraic** [comment]
Thanks @carnage, would appreciate that :).

**Comment by marcaube** [comment]
I got the same kind of result with tests using a data provider. Simply moving the data to an array inside the test case and looping on this data removed the false positives.

**Comment by padraic** [comment]
It is the data providers. The problem is that one of the older bits of pre-Humbug nameless library was the reliance on Junit which is fairly complex for our needs. There's a bug in there around the testsuite nesting. I'd fix it, but honestly I'd prefer to spend the time moving onwards to our own time logging solution which is JSON, simpler, and provides the option of finer grained test aggregation (at present, Humbug is limited to test CLASS aggregation due to PHPUnit limitations which means we run a lot of pointless tests - shall be optional since test insulation is not guaranteed, but a welcome perf boost for those who can swing it).

**Comment by padraic** [comment]
@carnage @marcaube Guys, give the new master a trial run - do a composer update first. Hopefully this resolves any data provider issues.

**Comment by marcaube** [comment]
@padraic It works fine for me now. Thanks!

**Comment by carnage** [comment]
@padraic Fixed it for me as well.

**Comment by padraic** [comment]
Excellent! :P
