### ISSUE TITLE
Error in WildCard Testsuite paths

### ISSUE THREAD

**Issue by jg-development** [padraic/humbug#59]
Since the commit https://github.com/padraic/humbug/commit/93d47cf9600d94b7bb17631923970234214089d7
the testsuite search results in an error like:
Could not find file 4DevelopmentOnly/tests/unit//./module working from /var/www/foo/4DevelopmentOnly/tests/unit
The Problem is in Line 118 with the $path. In the past, it was the nodeValue with ./module,
now it is "4DevelopmentOnly/tests/unit//./module" with the working directory "/var/www/foo/4DevelopmentOnly/tests/unit".
This cannot work anymore.. plz revert until fully comp or plz fix it.
Greetings Jan

```
{
  "chdir": "4DevelopmentOnly/tests/unit",
  "timeout": 10,
  "source": {
    "directories": [
      "."
    ],
    "excludes": [
      "4DevelopmentOnly",
      "vendor"
    ]
  },
  "logs": {
    "text": "build/humbuglog.txt"
  }
}
```

**Comment by pfrenssen** [comment]
Indeed I introduced a bug here. I wasn't taking the 'chdir' use case into account. The `getcwd()` solution seems to work fine.

**Comment by padraic** [comment]
Note: It's clear that I need to take a timeout and show the unit tests a little love. That will be my priority over the coming week. I thoroughly enjoyed writing Humbug over the holidays, but there is a cost attached to reworking older legacy code and "getting stuff done because it's fun". I don't want you guys paying for my technical debt all the time. Time to nigh to expand the test suite and wheel out behat for the console ops.

**Comment by jg-development** [comment]
Hi,
thanks for the support, maybe we can help you a little. I think I have a little time to write some Tests too.
Just wait for the pull requests ;-)
Greetings Jan

**Comment by pfrenssen** [comment]
@padraic thanks for your hard work on this. Don't worry about the rough edges, these will be straightened out in time!
