### ISSUE TITLE
certain mutants are impossible to cover

### ISSUE THREAD

**Issue by konforce** [padraic/humbug#70]
I have a fully covered codebase that I tried humbug on, but to my surprise it claimed some mutants were uncovered. After some digging around, I found that it will try to create mutants for the following:

```php
class FooBar
{
  protected $a = 0;

  public function foo()
  {
    return $a;
  }

  public function bar($b = 0)
  {
    return $b;
  }
}
```

Even if I were to write a test that covered `foo()` and `bar()`, PHP's code coverage won't claim that either lines with `$a=0` or `$b=0` are covered.

Is there a way to work around this behavior with options for either PHPUnit or humbug?

If not, my initial thoughts are:

* If 'method' is ???, then add all tests that cover the class. So, to test the mutant `$a = 1`, any test that covers FooBar should be run.

* If the mutant is on a function declaration, then add all tests that cover any part of the function (i.e., the first line of code in the function).

Otherwise, it's kind of annoying to have a report with uncovered mutants (which I actually didn't find a way to figure out what they are, without hacking humbug) that you cannot do anything about.

**Comment by padraic** [comment]
You're picking the hard pieces ;). No, seriously, you are correct - Humbug is mutating entire files without regard for how we use code coverage line checks. It's down to be fixed, but I'll save you the annoyance of overreporting by limiting it to method blocks until I get the future backend time/coverage logging cleaned up.

Fixed with https://github.com/padraic/humbug/commit/39c2cdfc9135dda83b0f4f4f0b7c4880e766f112
