### ISSUE TITLE
Write Log File after Tests are completed

### ISSUE THREAD

**Issue by jg-development** [padraic/humbug#81]
It would be nice, if the log files were written after the tests are completed.
The log files shouldnt be deleted at the beginning of the tests.
An analysis of the errors etc. is so longer possible.

**Comment by padraic** [comment]
You mean the text/json logs? These are overwritten at the end of each Humbug run. The old logs won't tell you anything about a new Humbug cycle. In fact, the text log is written to incrementally as Humbug progresses because it makes a bit of debugging possible when something causes an unexpected failure.

You may be suggesting something like timestamped logs which would be a naming issue?
